### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by Autumnlight02** [mattfletcher94/twrpc#2]
Is this package still maintained? I am building something similar at the moment, only difference is that i go the exact same routing pattern like trpc.

**Comment by mattfletcher94** [comment]
Hi @Autumnlight02, this package is still maintained.

I would also prefer to use the same pattern as TRPC, but my Typescript knowledge isn't quite good enough.

Do you have some ideas on how this might be done?

**Comment by Autumnlight02** [comment]
@mattfletcher94 do you have discord? IV'e started working on it and already have a path to archieve what we want, but there are some design discussions open. I think think it makes quite sense to implement it 1 to 1 like trpc. So I would like to discuss in a rapid fashion on how we would should let it look / feel like

**Comment by Autumnlight02** [comment]
as an example, a discussion if procedures are needed, if we should have query and mutate as well, if we should add middlewares, etc etc.

**Comment by mattfletcher94** [comment]
@Autumnlight02 sounds great, I will dm you

**Comment by mattfletcher94** [comment]
> @mattfletcher94 do you have discord? IV'e started working on it and already have a path to archieve what we want, but there are some design discussions open. I think think it makes quite sense to implement it 1 to 1 like trpc. So I would like to discuss in a rapid fashion on how we would should let it look / feel like

Sounds great - please find me on discord mattfletcher941607
